<a href="https://colab.research.google.com/github/Sushila-Phogat/CE888/blob/master/Lab1/Basics_Revision.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Python Data Types

In [3]:
#Python Numbers
a = 5
print(a, "is of type", type(a))

a = 2.0
print(a, "is of type", type(a))

a = 1+2j
print(a, "is complex number?", isinstance(1+2j,complex))

5 is of type <class 'int'>
2.0 is of type <class 'float'>
(1+2j) is complex number? True


In [23]:
#Python List
a = [5,10,15,20,25,30,35,40]

print("list a is",a)
# a[2] = 15
print("a[2] = ", a[2]) #Lists are mutable, meaning, value of elements of a list can be altered.

# a[0:3] = [5, 10, 15]
print("a[0:3] = ", a[0:3]) 

# a[5:] = [30, 35, 40]
print("a[5:] = ", a[5:])

#####Slicing##################
nums = list(range(5))     # range is a built-in function that creates a list of integers
print(nums)               # Prints "[0, 1, 2, 3, 4]"
print(nums[2:4])          # Get a slice from index 2 to 4 (exclusive); prints "[2, 3]"
print(nums[2:])           # Get a slice from index 2 to the end; prints "[2, 3, 4]"
print(nums[:2])           # Get a slice from the start to index 2 (exclusive); prints "[0, 1]"
print(nums[:])            # Get a slice of the whole list; prints "[0, 1, 2, 3, 4]"
print(nums[:-1])          # Slice indices can be negative; prints "[0, 1, 2, 3]"
nums[2:4] = [8, 9]        # Assign a new sublist to a slice
print(nums)               # Prints "[0, 1, 8, 9, 4]"

########normal functions################
xs = [3, 1, 2]    # Create a list
print(xs, xs[2])  # Prints "[3, 1, 2] 2"
print(xs[-1])     # Negative indices count from the end of the list; prints "2"
xs[2] = 'foo'     # Lists can contain elements of different types
print(xs)         # Prints "[3, 1, 'foo']"
xs.append('bar')  # Add a new element to the end of the list
print(xs)         # Prints "[3, 1, 'foo', 'bar']"
x = xs.pop()      # Remove and return the last element of the list
print(x, xs)      # Prints "bar [3, 1, 'foo']"

animals = ['cat', 'dog', 'monkey']
for idx, animal in enumerate(animals):
    print('#%d: %s' % (idx + 1, animal))
# Prints "#1: cat", "#2: dog", "#3: monkey", each on its own line

list a is [5, 10, 15, 20, 25, 30, 35, 40]
a[2] =  15
a[0:3] =  [5, 10, 15]
a[5:] =  [30, 35, 40]
[0, 1, 2, 3, 4]
[2, 3]
[2, 3, 4]
[0, 1]
[0, 1, 2, 3, 4]
[0, 1, 2, 3]
[0, 1, 8, 9, 4]
[3, 1, 2] 2
2
[3, 1, 'foo']
[3, 1, 'foo', 'bar']
bar [3, 1, 'foo']
#1: cat
#2: dog
#3: monkey


In [6]:
  #Python Tuple
  ##Tuple is an ordered sequence of items same as list.The only difference is that tuples are immutable. Tuples once created cannot be modified.
  ##Tuples are used to write-protect data and are usually faster than list as it cannot change dynamically.
  ##It is defined within parentheses () where items are separated by commas.
  t = (5,'program', 1+3j)

# t[1] = 'program'
print("t[1] = ", t[1])

# t[0:3] = (5, 'program', (1+3j))
print("t[0:3] = ", t[0:3])

# Generates error
# Tuples are immutable
t[0] = 10

t[1] =  program
t[0:3] =  (5, 'program', (1+3j))


TypeError: ignored

In [8]:
#Python Strings
##String is sequence of Unicode characters.
## We can use single quotes or double quotes to represent strings. Multi-line strings can be denoted using triple quotes, ''' or """.
##Like list and tuple, slicing operator [ ] can be used with string. Strings are immutable.
s = 'Hello world!'

# s[4] = 'o'
print("s[4] = ", s[4])

# s[6:11] = 'world'
print("s[6:11] = ", s[6:11])

# Generates error
# Strings are immutable in Python
s[5] ='d'

s[4] =  o
s[6:11] =  world


TypeError: ignored

In [22]:
#Python Set
##Set is an unordered collection of unique items. Set is defined by values separated by comma inside braces { }. Items in a set are not ordered.
a = {5,2,3,1,4}

# printing set variable
print("a = ", a)


# data type of variable a
print(type(a))

#We can perform set operations like union, intersection on two sets. Set have unique values. They eliminate duplicates.
a = {1,2,2,3,3,3}
print(a)
b={2,3,3,4,5}
#union 
print("all points in a and b",(a|b))
# intersection
print("common points in a and b",(a&b))
#different
print("points in a but not in  b",(a-b))
print(a.difference(b))
#Symmetric Difference -----Symmetric Difference of A and B is a set of elements in both A and B except those that are common in both.
print("all points except common points in a and b",(a^b))

#Discard-----The discard() removes element x from the set if the element is present.
numbers = {2, 3, 4, 5}

numbers.discard(3)
print('numbers = ', numbers)

#Subset and Superset
A = {1, 2, 3}
B = {1, 2, 3, 4, 5}
C = {1, 2, 4, 5}

# Returns True
print(A.issubset(B))
print(B.issuperset(C))

a =  {1, 2, 3, 4, 5}
<class 'set'>
{1, 2, 3}
all points in a and b {1, 2, 3, 4, 5}
common points in a and b {2, 3}
points in a but not in  b {1}
{1}
all points except common points in a and b {1, 4, 5}
numbers =  {2, 4, 5}
True
True


In [31]:
#Python Dictionary
###Dictionary is an unordered collection of key-value pairs.
###It is generally used when we have a huge amount of data. Dictionaries are optimized for retrieving data. We must know the key to retrieve the value.
d = {1:'value','key':2}
print(type(d))

print("d[1] = ", d[1]);

print("d['key'] = ", d['key']);

print(d.get('monkey', 'N/A'))  # Get an element with a default; prints "N/A"
print(d.get(1))    # Get an element with a default; prints "value"
del d['1']         # Remove an element from a dictionary
print(d.get(1, 'N/A')) # "1" is no longer a key; prints "N/A"

<class 'dict'>
d[1] =  value
d['key'] =  2
N/A
value


KeyError: ignored

In [32]:
class Greeter(object):

    # Constructor
    def __init__(self, name):
        self.name = name  # Create an instance variable

    # Instance method
    def greet(self, loud=False):
        if loud:
            print('HELLO, %s!' % self.name.upper())
        else:
            print('Hello, %s' % self.name)

g = Greeter('Fred')  # Construct an instance of the Greeter class
g.greet()            # Call an instance method; prints "Hello, Fred"
g.greet(loud=True)   # Call an instance method; prints "HELLO, FRED!"

Hello, Fred
HELLO, FRED!


#Numpy

In [46]:
import numpy as np

x = np.array([1, 2])   # Let numpy choose the datatype
print(x.dtype)         # Prints "int64"

x = np.array([1.0, 2])   # Let numpy choose the datatype
print(x.dtype)             # Prints "float64"

x = np.array([1, 2], dtype=np.int64)   # Force a particular datatype
print(x.dtype)

# Creating a rank 2 Array
arr = np.array([[1, 2, 3],
                [4, 5, 6]])
print("Array with Rank 2: \n", arr)
 
# Creating an array from tuple
arr = np.array((1, 3, 2))
print("\nArray created using " "passed tuple:\n", arr)

# indexing in numpy array
 
# Initial Array
arr = np.array([[-1, 2, 0, 4],
                [4, -0.5, 6, 0],
                [2.6, 0, 7, 8],
                [3, -7, 4, 2.0]])
print("Initial Array: ")
print(arr)
 
# Printing a range of Array
# with the use of slicing method
sliced_arr = arr[:2, ::2]
print ("Array with first 2 rows and"
    " alternate columns(0 and 2):\n", sliced_arr)
 
# Printing elements at
# specific Indices
Index_arr = arr[[1, 1, 0, 3], 
                [3, 2, 1, 0]]
print ("\nElements at indices (1, 3), "
    "(1, 2), (0, 1), (3, 0):\n", Index_arr)

# sum of array elements
# Performing Unary operations
print ("\nSum of all array "
       "elements: ", arr.sum(),np.sum(arr))

# Transpose of Array
# using In-built function 'T'
print("\nTranspose of Array: ")
print(arr.T)

x = np.array([[1,2],[3,4]])
y = np.array([[5,6],[7,8]])

v = np.array([9,10])
w = np.array([11, 12])

# Inner product of vectors; both produce 219
print(v.dot(w))
print(np.dot(v, w))

# Matrix / vector product; both produce the rank 1 array [29 67]
print(x.dot(v))
print(np.dot(x, v))

# Matrix / matrix product; both produce the rank 2 array
# [[19 22]
#  [43 50]]
print(x.dot(y))
print(np.dot(x, y))

int64
float64
int64
Array with Rank 2: 
 [[1 2 3]
 [4 5 6]]

Array created using passed tuple:
 [1 3 2]
Initial Array: 
[[-1.   2.   0.   4. ]
 [ 4.  -0.5  6.   0. ]
 [ 2.6  0.   7.   8. ]
 [ 3.  -7.   4.   2. ]]
Array with first 2 rows and alternate columns(0 and 2):
 [[-1.  0.]
 [ 4.  6.]]

Elements at indices (1, 3), (1, 2), (0, 1), (3, 0):
 [0. 6. 2. 3.]

Sum of all array elements:  34.1 34.1

Transpose of Array: 
[[-1.   4.   2.6  3. ]
 [ 2.  -0.5  0.  -7. ]
 [ 0.   6.   7.   4. ]
 [ 4.   0.   8.   2. ]]
219
219
[29 67]
[29 67]
[[19 22]
 [43 50]]
[[19 22]
 [43 50]]
