<a href="https://colab.research.google.com/github/Sushila-Phogat/CE888/blob/master/Lab5/my_recommender.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [152]:
import pandas as pd
import numpy as np

# Assign spreadsheet filename: file
file = 'https://github.com/Sushila-Phogat/CE888/blob/master/jester-data-1.xls?raw=true'

# Load spreadsheet: xl
xl = pd.ExcelFile(file)

# Load a sheet into a DataFrame by name: df1
df1 = xl.parse(0)



df1.drop(df1.columns[[0]], axis = 1, inplace = True) 

df1.head(5)

-7.82   8.79  -9.66  -8.16  -7.52  ...  99.22  -5.63  99.23  99.24  99.25
0   4.08  -0.29   6.36   4.37  -2.38  ...  -2.14   3.06   0.34  -4.32   1.07
1  99.00  99.00  99.00  99.00   9.03  ...  99.00  99.00  99.00  99.00  99.00
2  99.00   8.35  99.00  99.00   1.80  ...  99.00  99.00  99.00  99.00  99.00
3   8.50   4.61  -4.17  -5.39   1.36  ...   1.55   3.11   6.55   1.80   1.60
4  -6.17  -3.54   0.44  -8.50  -7.09  ...  -3.35   0.05  -9.08  -5.05  -3.45

[5 rows x 100 columns]

In [153]:
print(df1.shape)

(24982, 100)


In [154]:
df1.describe()

-7.82          8.79  ...         99.24         99.25
count  24982.000000  24982.000000  ...  24982.000000  24982.000000
mean      34.403125     27.094822  ...     55.751626     60.136534
std       46.707230     44.228739  ...     49.237364     47.913859
min       -9.950000     -9.950000  ...     -9.950000     -9.950000
25%       -0.150000     -2.180000  ...      1.322500      3.930000
50%        5.050000      3.690000  ...     99.000000     99.000000
75%       99.000000     99.000000  ...     99.000000     99.000000
max       99.000000     99.000000  ...     99.000000     99.000000

[8 rows x 100 columns]

In [155]:
arr = df1.values
print(arr.shape)
rated = np.where(arr!=99)
print(len(rated[0]), rated[1].shape)

(24982, 100)
1810381 (1810381,)


In [156]:
print(arr)
print(np.where(arr!=99))

[[ 4.08 -0.29  6.36 ...  0.34 -4.32  1.07]
 [99.   99.   99.   ... 99.   99.   99.  ]
 [99.    8.35 99.   ... 99.   99.   99.  ]
 ...
 [99.   99.   99.   ... 99.   99.   99.  ]
 [99.   99.   99.   ... 99.   99.   99.  ]
 [ 2.43  2.67 -3.98 ... 99.   99.   99.  ]]
(array([    0,     0,     0, ..., 24981, 24981, 24981]), array([ 0,  1,  2, ..., 69, 70, 86]))


In [0]:

def replace(orig, percentage=0.1):
  """
  Replaces 'percentage'% of the original values in 'orig' with 99's
  :param orig: original data array
  :param percentage: percentage of values to replace (0<percentage<1)
  """
  new_data = orig.copy()
  rated = np.where(arr!=99)
  n_rated = len(rated[0])
  idx = np.random.choice(n_rated, size=int(percentage*n_rated), replace=False)
  new_data[rated[0][idx], rated[1][idx]] = 99
  return new_data, (rated[0][idx], rated[1][idx])

In [0]:
new_arr, idx = replace(arr, 0.1)

In [159]:
arr[idx[0][0], idx[1][0]]

7.62

In [160]:
new_arr[idx[0][0], idx[1][0]]

99.0

In [0]:
import pandas as pd
import numpy as np
from IPython.display import Image
np.set_printoptions(precision = 3)

In [162]:
df1.shape[0]

24982

In [0]:
n_latent_factors = 2

user_ratings = df1.values
# Initialise as random values
latent_user_preferences = np.random.random((df1.shape[0], n_latent_factors))
latent_item_features = np.random.random((df1.shape[1], n_latent_factors))

In [164]:
latent_item_features.shape[0]

100

In [165]:
latent_user_preferences

array([[0.023, 0.684],
       [0.774, 0.853],
       [0.527, 0.967],
       ...,
       [0.9  , 0.004],
       [0.539, 0.186],
       [0.049, 0.212]])

In [0]:
def predict_rating(user_id, item_id):
    """ Predict a rating given a user_id and an item_id.
    """
    user_preference = latent_user_preferences[user_id]
    item_preference = latent_item_features[item_id]
    return user_preference.dot(item_preference)


def train(user_id, item_id, rating, alpha=0.0001):
  prediction_rating = predict_rating(user_id, item_id)
  err =  prediction_rating - rating
  user_pref_values = latent_user_preferences[user_id][:]
  latent_user_preferences[user_id] -= alpha * err * latent_item_features[item_id]
  latent_item_features[item_id] -= alpha * err * user_pref_values
  return err
    

def sgd(iterations=300000):
  for iteration in range(iterations):
    error=[]
    for user_id in range(latent_user_preferences.shape[0]):
      for item_id in range(latent_item_features.shape[0]):
        rating = user_ratings[user_id][item_id]
        if not np.isnan(rating):
          err = train(user_id, item_id, rating)
          error.append(err)
          mse = (np.array(error) ** 2).mean()
          if (iteration % 10000) == 0:
            print(mse)

In [167]:
sgd()

Streaming output truncated to the last 5000 lines.
2602.98460209318
2602.5580705761595
2602.1227653901337
2601.684759414606
2601.254650978579
2600.8226624353792
2600.3960133399733
2599.961460893555
2599.5247607200586
2599.090211762634
2598.653993566223
2598.217743696324
2597.783661173981
2597.3587398632903
2596.9228212159064
2596.489013332689
2596.0625719006016
2595.635333435762
2595.206515247757
2594.7758062328026
2594.3495096384895
2593.915967334726
2593.4835079215836
2593.056169259417
2592.624425658516
2592.1988186409226
2591.767988343205
2591.333455711672
2590.9026719328194
2590.474155450675
2590.0507184695716
2589.6175899154678
2589.1866549667716
2588.7591451321264
2589.958580697897
2591.156735857412
2592.337193598486
2593.5203273515385
2594.707795130291
2595.885558248169
2597.0665432734045
2598.241338800769
2599.4306219179402
2600.6228695336904
2601.8022388055188
2602.992114753857
2604.179133346173
2605.3442657671794
2606.5182620681603
2607.682454042072
2608.859273982868
2610.043

KeyboardInterrupt: ignored

In [168]:

predictions = latent_user_preferences.dot(latent_item_features.T)
predictions

array([[0.363, 0.396, 0.337, ..., 1.028, 0.65 , 0.597],
       [0.801, 1.12 , 1.491, ..., 2.662, 2.094, 1.848],
       [0.807, 1.064, 1.307, ..., 2.579, 1.937, 1.724],
       ...,
       [0.228, 0.476, 0.899, ..., 1.007, 1.015, 0.864],
       [0.23 , 0.385, 0.618, ..., 0.865, 0.77 , 0.666],
       [0.12 , 0.14 , 0.14 , ..., 0.355, 0.24 , 0.218]])

In [0]:
values = [zip(user_ratings[i], predictions[i]) for i in range(predictions.shape[0])]
comparison_data = pd.DataFrame(values)
comparison_data.columns = df1.columns

In [196]:
#Best joke
df_mean=[]
df_mean.append(df1.mean(axis = 0, skipna = True))

type(df_mean)
df_mean[-1].sort_values(ascending=False).head(1)


99.1    65.510407
dtype: float64

In [197]:
#worst joke
df_mean=df1.mean(axis = 0, skipna = True)
df_mean.sort_values(ascending=True).head(1) #53th is wort joke

-7.52.1   -3.071944
dtype: float64