<a href="https://colab.research.google.com/github/Sushila-Phogat/CE888/blob/master/Lab5/my_recommender.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [90]:
import pandas as pd
import numpy as np

# Assign spreadsheet filename: file

df1 =pd.read_excel('https://github.com/Sushila-Phogat/CE888/blob/master/jester-data-1.xls?raw=true', header=None)



df1.drop(df1.columns[[0]], axis = 1, inplace = True) 

df1.head(5)

1      2      3      4     5    ...    96     97     98     99     100
0  -7.82   8.79  -9.66  -8.16 -7.52  ...  99.00  -5.63  99.00  99.00  99.00
1   4.08  -0.29   6.36   4.37 -2.38  ...  -2.14   3.06   0.34  -4.32   1.07
2  99.00  99.00  99.00  99.00  9.03  ...  99.00  99.00  99.00  99.00  99.00
3  99.00   8.35  99.00  99.00  1.80  ...  99.00  99.00  99.00  99.00  99.00
4   8.50   4.61  -4.17  -5.39  1.36  ...   1.55   3.11   6.55   1.80   1.60

[5 rows x 100 columns]

In [91]:
print(df1.shape)

(24983, 100)


In [92]:
df1.describe()

1             2    ...           99            100
count  24983.000000  24983.000000  ...  24983.000000  24983.000000
mean      34.401435     27.094089  ...     55.753357     60.138090
std       46.707059     44.228006  ...     49.237139     47.913531
min       -9.950000     -9.950000  ...     -9.950000     -9.950000
25%       -0.150000     -2.180000  ...      1.335000      3.930000
50%        5.050000      3.690000  ...     99.000000     99.000000
75%       99.000000     99.000000  ...     99.000000     99.000000
max       99.000000     99.000000  ...     99.000000     99.000000

[8 rows x 100 columns]

In [93]:
arr = df1.values
print(arr.shape)
rated = np.where(arr!=99)
print(len(rated[0]), rated[1].shape)

(24983, 100)
1810455 (1810455,)


In [94]:
print(arr)
print(np.where(arr!=99))

[[-7.82  8.79 -9.66 ... 99.   99.   99.  ]
 [ 4.08 -0.29  6.36 ...  0.34 -4.32  1.07]
 [99.   99.   99.   ... 99.   99.   99.  ]
 ...
 [99.   99.   99.   ... 99.   99.   99.  ]
 [99.   99.   99.   ... 99.   99.   99.  ]
 [ 2.43  2.67 -3.98 ... 99.   99.   99.  ]]
(array([    0,     0,     0, ..., 24982, 24982, 24982]), array([ 0,  1,  2, ..., 69, 70, 86]))


In [0]:

def replace(orig, percentage=0.1):
  """
  Replaces 'percentage'% of the original values in 'orig' with 99's
  :param orig: original data array
  :param percentage: percentage of values to replace (0<percentage<1)
  """
  new_data = orig.copy()
  rated = np.where(arr!=99)
  n_rated = len(rated[0])
  idx = np.random.choice(n_rated, size=int(percentage*n_rated), replace=False)
  new_data[rated[0][idx], rated[1][idx]] = 99
  return new_data, (rated[0][idx], rated[1][idx])

In [0]:
new_arr, idx = replace(arr, 0.1)

In [97]:
arr[idx[0][0], idx[1][0]]

8.3

In [98]:
new_arr[idx[0][0], idx[1][0]]

99.0

In [0]:
import pandas as pd
import numpy as np
from IPython.display import Image
np.set_printoptions(precision = 3)

In [0]:
n_latent_factors = 2

user_ratings = df1.values
# Initialise as random values
latent_user_preferences = np.random.random((df1.shape[0], n_latent_factors))
latent_item_features = np.random.random((df1.shape[1], n_latent_factors))

In [101]:
latent_item_features.shape[0]

100

In [102]:
latent_user_preferences.shape[0]

24983

In [0]:
def predict_rating(user_id, item_id):
    """ Predict a rating given a user_id and an item_id.
    """
    user_preference = latent_user_preferences[user_id]
    item_preference = latent_item_features[item_id]
    return user_preference.dot(item_preference)


def train(user_id, item_id, rating, alpha=0.001):
  prediction_rating = predict_rating(user_id, item_id)
  err =  prediction_rating - rating
  user_pref_values = latent_user_preferences[user_id][:]
  latent_user_preferences[user_id] -= alpha * err * latent_item_features[item_id]
  latent_item_features[item_id] -= alpha * err * user_pref_values
  return err
    

def sgd(iterations=10):
  for iteration in range(iterations):
    error=[]
    for user_id in range(latent_user_preferences.shape[0]):
      for item_id in range(latent_item_features.shape[0]):
        rating = user_ratings[user_id][item_id]
        if (rating!=99):
          err = train(user_id, item_id, rating)
          error.append(err)
    mse = (np.array(error) ** 2).mean()
    #if the iteration multiple of 10000
    if (iteration % 1) == 0:
      print(mse)

In [104]:
sgd()

24.351121887917394
21.52917068258157
18.728175468465462
17.8150686218577
17.71893439269095
17.74828856902953
17.825218341173724
17.947768757637256
18.14237467101266
18.467937635488113


In [111]:

predictions = latent_user_preferences.dot(latent_item_features.T)
predictions

array([[-2.829, -3.314, -5.059, ..., -1.486, -6.811, -1.314],
       [ 1.38 ,  1.582,  2.079, ...,  1.106,  2.596,  1.11 ],
       [ 6.546,  7.323,  7.777, ...,  7.291,  8.423,  7.787],
       ...,
       [ 0.457,  0.523,  0.672, ...,  0.384,  0.828,  0.389],
       [-0.792, -0.961, -1.792, ..., -0.049, -2.607,  0.085],
       [ 4.023,  4.474,  4.474, ...,  4.781,  4.605,  5.155]])

In [0]:
values = [zip(user_ratings[i], predictions[i]) for i in range(predictions.shape[0])]
comparison_data = pd.DataFrame(values)
comparison_data.columns = df1.columns

In [113]:
comparison_data

1    ...                          100
0      (-7.82, -2.8286436957418144)  ...  (99.0, -1.3138223152867674)
1        (4.08, 1.3795439296794132)  ...   (1.07, 1.1103237302912403)
2         (99.0, 6.545689698214202)  ...    (99.0, 7.786924577057685)
3        (99.0, 1.1900235648950461)  ...   (99.0, 2.3162474337881975)
4         (8.5, 3.1289215472695155)  ...     (1.6, 4.457393993208103)
...                             ...  ...                          ...
24978     (0.44, 4.293966879524273)  ...    (7.43, 5.570313545571781)
24979    (9.13, 0.5136108487736056)  ...  (8.45, -0.2752193456951821)
24980   (99.0, 0.45749735448706147)  ...   (99.0, 0.3891867285771356)
24981   (99.0, -0.7921193087253241)  ...  (99.0, 0.08472118324348034)
24982     (2.43, 4.022770244081067)  ...     (99.0, 5.15503414335596)

[24983 rows x 100 columns]

In [115]:
predictions.mean(axis = 0)

array([ 0.706,  0.74 ,  0.266, -1.163,  0.53 ,  1.615, -0.302, -0.721,
       -0.93 ,  0.497,  1.616,  1.9  , -1.496,  1.938, -1.961, -3.062,
       -0.635, -0.939,  0.126, -0.951,  2.567,  0.931, -0.081, -1.931,
        0.692,  1.754,  3.053,  1.484,  3.103, -0.513,  2.515,  3.052,
       -1.28 ,  1.346,  2.988,  3.044, -1.533,  0.818,  1.476,  1.065,
       -0.757,  2.237, -1.137, -2.737,  1.007,  1.589,  1.617,  1.802,
        2.835,  3.405, -0.333,  0.151,  3.114,  2.832,  0.186,  2.112,
       -2.473, -3.761, -0.649, -1.088,  2.456,  2.701,  0.07 , -1.115,
        2.622,  2.538, -1.271,  2.506,  2.716,  0.599, -1.014,  2.56 ,
        1.12 , -1.31 , -0.368,  2.127,  0.546,  1.394,  0.112,  1.188,
        1.766,  0.494,  1.978,  0.426,  0.721, -0.323,  1.543,  1.579,
        2.885,  0.171,  1.447,  0.898,  2.096,  0.215,  0.5  ,  0.918,
        1.082,  1.348, -0.161,  1.532])

In [180]:
#Best joke
predictions_mean=[]
predictions_mean.append(predictions.mean(axis = 0))
#predictions_mean[-1].sort_values(ascending=False).head(1)
#predictions.mean(axis = 0)[-1].sort_values(ascending=False).head(1)

print("Best joke is: and its mean value is : ", np.argmax(predictions_mean[-1])+1,np.max(predictions_mean[-1]))

Best joke is: and its mean value is :  50 3.4049566190899037


In [181]:
#worst joke
print("Best joke is: and its mean value is : ", np.argmin(predictions_mean[-1])+1,np.min(predictions_mean[-1]))

Best joke is: and its mean value is :  58 -3.760899103133236
